version: '3'

services:
  php:
    build: ./docker/php
    volumes:
      - ./:/app
    working_dir: /app
  database:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
    ports:
      - '5496:5432'
    volumes:
      - ./var/db-data:/var/lib/postgresql/data
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./:/app
      - ./docker/nginx:/etc/nginx/conf.d
